<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="utf-8" />
    <title>MVC template</title>
</head>

<body>
    <header>
        <nav>
            <ul>
                <li>
                    <a href="index.php">Accueil</a>
                </li>
                <li>
                    <a href="index.php?route=a-propos">À propos</a>
                </li>
            </ul>
        </nav>
    </header>
    <?php
    if ($route === 'home') {
        require 'templates/home.phtml';
    } else if ($route === 'about') {
        require 'templates/about.phtml';
    } else if ($route === 'contact') {
        require 'templates/contact.phtml';
    } else if ($route === 'error') {
        require 'templates/error.phtml';
    }

    ?>
</body>

</html>